//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Audit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuditEventFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuditEventFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Audit.AuditEventFile", typeof(AuditEventFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} is unsuccessfully authenticated..
        /// </summary>
        internal static string AuthentificationFailed {
            get {
                return ResourceManager.GetString("AuthentificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} is successfully authenticated..
        /// </summary>
        internal static string AuthentificationSuccess {
            get {
                return ResourceManager.GetString("AuthentificationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} failed to access {1}. Reason: {2}..
        /// </summary>
        internal static string AuthorizationFailed {
            get {
                return ResourceManager.GetString("AuthorizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} successfully accessed to {1}..
        /// </summary>
        internal static string AuthorizationSuccess {
            get {
                return ResourceManager.GetString("AuthorizationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to access the DataBase. Reason: {0}..
        /// </summary>
        internal static string DataBaseAccessFailed {
            get {
                return ResourceManager.GetString("DataBaseAccessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully accessed the DataBase. Message: {0}..
        /// </summary>
        internal static string DataBaseAccessSuccess {
            get {
                return ResourceManager.GetString("DataBaseAccessSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with username: {0} successfully Login..
        /// </summary>
        internal static string LoginAttemptSuccess {
            get {
                return ResourceManager.GetString("LoginAttemptSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with username {0} failed to Login. Reason: {1}..
        /// </summary>
        internal static string LoginAttemtpFailed {
            get {
                return ResourceManager.GetString("LoginAttemtpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with username {0} failed to Logout. Reason: {1}..
        /// </summary>
        internal static string LogoutAttemptFailed {
            get {
                return ResourceManager.GetString("LogoutAttemptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with username: {0} successfully Logout..
        /// </summary>
        internal static string LogoutAttemptSuccess {
            get {
                return ResourceManager.GetString("LogoutAttemptSuccess", resourceCulture);
            }
        }
    }
}
